### ISSUE TITLE
Test run fails: `Error in `initializePtr()`: function 'chm_factor_ldetL2' not provided by package 'Matrix'`

### ISSUE THREAD

**Issue by barracuda156** [WillTirone/modelfactory#2]
```

R version 4.3.3 (2024-02-29) -- "Angel Food Cake"
Copyright (C) 2024 The R Foundation for Statistical Computing
Platform: powerpc-apple-darwin10.0.0d2 (32-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> # This file is part of the standard setup for testthat.
> # It is recommended that you do not modify it.
> #
> # Where should you do additional test configuration?
> # Learn more about the roles of various files in:
> # * https://r-pkgs.org/tests.html
> # * https://testthat.r-lib.org/reference/test_package.html#special-files
> 
> library(testthat)
> library(modelfactory)
> 
> test_check("modelfactory")
Waiting for profiling to be done...
Waiting for profiling to be done...
Waiting for profiling to be done...
[ FAIL 1 | WARN 0 | SKIP 0 | PASS 0 ]

══ Failed tests ════════════════════════════════════════════════════════════════
── Error ('test-combine.R:18:1'): (code run outside of `test_that()`) ──────────
Error in `initializePtr()`: function 'chm_factor_ldetL2' not provided by package 'Matrix'
Backtrace:
     ▆
  1. └─lme4::lmer(Sepal.Length ~ (1 | Species), data = iris) at test-combine.R:18:1
  2.   ├─base::do.call(...)
  3.   └─lme4 (local) `<fn>`(...)
  4.     ├─base::do.call(...)
  5.     └─methods (local) `<rfMthdDf>`(...)
  6.       └─methods::new(def, ...)
  7.         ├─methods::initialize(value, ...)
  8.         └─methods::initialize(value, ...)
  9.           └─.Object$initialize(...)
 10.             └─lme4 (local) initializePtr()

[ FAIL 1 | WARN 0 | SKIP 0 | PASS 0 ]
Error: Test failures
Execution halted
```

**Comment by WillTirone** [comment]
Hi! Yes, there's an issue with Matrix < 1.6.2 and >= 1.6.2. See [here](https://stackoverflow.com/questions/77481539/error-in-initializeptr-function-cholmod-factor-ldeta-not-provided-by-pack) for more details. 

Also, can I ask how you found this repo? Just curious :)

**Comment by barracuda156** [comment]
> Also, can I ask how you found this repo?

CRAN page refers to here :)
https://cran.r-project.org/web/packages/modelfactory/index.html

**Comment by WillTirone** [comment]
It does, but how did you find the CRAN page? Did you actually need to use the package for something or were you just browsing through CRAN?

**Comment by barracuda156** [comment]
I am maintaining `R`-related stuff in Macports and add packages which appear potentially useful or interesting.
It is unlikely I will personally use every of 4000+ R ports, even if I wish to, but hopefully somebody will. But I do use some `R` ports time to time myself too (primarily Bayesian modelling-related).

**Comment by WillTirone** [comment]
Oh that's wonderful, I'm glad you found it :) yeah, I think I'll close this issue since I believe it's up to the user to ensure they can fit lmer models outside of my package. If they can, the checks + tests should pass. lmer also isn't used for anything other than the examples.

**Comment by barracuda156** [comment]
You could add a requirement for the needed version of Matrix in DESCRIPTION, so that instead of an obscure failure a user sees a clear requirement :) And you do not get unnecessary tickets.

**Comment by WillTirone** [comment]
I will do that, thank you!!

**Comment by WillTirone** [comment]
Ah, I actually do have `Matrix (>= 1.6-5)` in the `Suggests:` chunk of the DESCRIPTION. Since `lmer` isn't actually used for the code I think it's okay to just suggest this version instead of require.

**Comment by barracuda156** [comment]
I guess I need to try revbumping `lme4` in Macports, which will trigger rebuild from source, and see if that resolves the problem.

**Comment by barracuda156** [comment]
So yeah, after rebuilding `lme4` from source, no issues with tests anymore, all good. Thank you.
